title: berzi.research
url: "https://berzi.hashnode.dev"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/spirizeon"
footer_text: "berzi.research"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "./"
 - name: "Resume"
   link: "resume"
 - name: "Contact"
   link: "contact"
 - name: "Blogs"
   link: "blogs"
